name: Testes de CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.0'

      - name: Instalar o biblioteca
        run: |
          python -m pip install --upgrade pip
          make install
      
      - name: Configurar variáveis de ambiente
        run: |
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> $GITHUB_ENV
          echo "FIRECRAWL_API_KEY=${{ secrets.FIRECRAWL_API_KEY }}" >> $GITHUB_ENV
          echo "SEARCHAPI_API_KEY=${{ secrets.SEARCHAPI_API_KEY }}" >> $GITHUB_ENV
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> $GITHUB_ENV
      - name: Verificar formação dos arquivos
        run: |
          make format
      - name: Verificar lint dos arquivos
        run: |
          make lint
      - name: Verificar testes dos arquivos
        run: |
          make test
      - name: Verificar typagem dos arquivos
        run: |
          make typepyright

